services:
  db:
    image: postgres:16
    container_name: spotify-insights-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: spotify_insights
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: